version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_mlb
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mlb_user:password123@db:5432/mlb_db
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: mlb_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mlb_db
    ports:
      - "5432:5432"
